In [1]:
import numpy as np

### 1
1. Создайте массив длины 10, заполненный нулями
2. Сделайте полученный массив неизменяемым

In [2]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
x = np.arange(4).reshape(2, 2)
x

array([[0, 1],
       [2, 3]])

In [4]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [5]:
y = x.T
y.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [6]:
z = x.reshape(4, 1)
z.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [7]:
x.flags.writeable = False
x[0] = 1

ValueError: assignment destination is read-only

## Constructing arrays

### 2
1. Создайте массив, содержащий 5 равноотстоящих точек, покрывающих диапазон от 0 до 2*pi
2. Создайте массив, содержащий 5 равноотстоящих в логарифмическом масштабе точек, покрывающих диапазон от 10 до 100
3. Составьте из полученных массивов координатную сеть (meshgrid)

In [8]:
x = np.linspace(0, 2*np.pi, 5)
y = np.logspace(1, 2, 5)
xx, yy = np.meshgrid(x, y)

In [9]:
xx, yy

(array([[0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531]]),
 array([[ 10.        ,  10.        ,  10.        ,  10.        ,
          10.        ],
        [ 17.7827941 ,  17.7827941 ,  17.7827941 ,  17.7827941 ,
          17.7827941 ],
        [ 31.6227766 ,  31.6227766 ,  31.6227766 ,  31.6227766 ,
          31.6227766 ],
        [ 56.23413252,  56.23413252,  56.23413252,  56.23413252,
          56.23413252],
        [100.        , 100.        , 100.        , 100.        ,
         100.        ]]))

In [10]:
def func(x, y):
    return 2 * x + y + 8

In [11]:
func(xx, yy)

array([[ 18.        ,  21.14159265,  24.28318531,  27.42477796,
         30.56637061],
       [ 25.7827941 ,  28.92438675,  32.06597941,  35.20757206,
         38.34916471],
       [ 39.6227766 ,  42.76436926,  45.90596191,  49.04755456,
         52.18914722],
       [ 64.23413252,  67.37572517,  70.51731783,  73.65891048,
         76.80050313],
       [108.        , 111.14159265, 114.28318531, 117.42477796,
        120.56637061]])

### 3
Создайте двумерный массив 5х5 с элементами 1, 2, 3 и 4 под главной диагональю, остальные элементы заполните нулями

In [12]:
x = np.array([1, 2, 3, 4])
x = np.diag(x, k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### 4
1. Создайте функцию-генератор, последовательно возвращающую целые числа от 0 до 9
2. Создайте массив из построенного генератора

In [13]:
def gen():
    for i in range(9):
        yield i

In [14]:
x = np.fromiter(gen(), dtype=int, count=-1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### 5

In [15]:
# "Что будет выведено на экран?
# a = np.arange(4).reshape(2,2)
# a += 0.5
# print(a)"

# Error: since we canot put a float to integer array 
# But if we do the following:
# a = np.arange(4).reshape(2,2)
# a = a + 0.5
# print(a)"
# It works!

### 6

In [16]:
#"Что будет выведено на экран?"
# a = np.array([1]) 
# if a:
#     print(True)
# else:
#     print(False)

# a = np.array([1, 2, 3])
# if a:
#     print(True)
# else:
#     print(False)


# Array contains only one element which is not None -> True
# Since array contains several elements, we cannot do comparison of the whole array -> Error

### 7

In [17]:
# "Что будет выведено на экран?
# print(0 * np.nan) 
# print(np.nan - np.nan)
# print(np.nan == np.nan)
# print(np.nan is np.nan)
# print(-np.inf < np.nan < np.inf)


# value * np.nan = np.nan always -> nan
# Any arithmetic operation with nan is nan -> nan
# False, cause we don't want to get np.nan - np.nan = 0 
# True
# nan is not a number -> False

### 8

In [18]:
# "Что будет выведено на экран?"
# print(np.isnan(np.array([np.nan]).astype(np.int)))

# False, since np.nan is a floating point value 

In [19]:
np.array([np.nan]).astype(int)

array([-9223372036854775808])

In [20]:
np.array([np.inf]).astype(int)

array([-9223372036854775808])

In [21]:
np.array([np.nan]).astype(float)

array([nan])

### 9
1. Создайте масив из четырех элементов: 0, 10, 20, 30
2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго,  больше предыдущего элемента этой же строки на 1.

In [22]:
x = np.array([0, 10, 20, 30]) # shape 4 

In [23]:
x = x.reshape(-1, 1) # shape 4 x 1
y = np.arange(5) # shape 5
z = x + y # shape 4 x 5
z

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

### 10
Какой shape будет у результата операции np.arange(5).reshape(1,-1) + np.arange(5).reshape(-1,1)? \
np.arange(5).reshape(1,-1) --- shape 1 x 5 \
np.arange(5).reshape(-1,1) --- shape 5 x 1 \
following the broadcasting rules -> shape 5 x 5

In [24]:
np.arange(5).reshape(1, -1) + np.arange(5).reshape(-1, 1)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

### 11
Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке

In [25]:
x = np.zeros((8, 8))
x[::2, ::2] = 1
x[1::2, 1::2] = 1
x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

### 12
1. Создайте одномерный массив целых чисел от 1 до 5
2. Вставьте 0 между каждой парой соседних элементов

In [26]:
x = np.arange(1, 6)
y = np.zeros(9)
y[::2] = x
y

array([1., 0., 2., 0., 3., 0., 4., 0., 5.])

### 13

In [27]:
# "Что будет выведено на экран?"
# x = np.arange(36).reshape(2, 3, 2, 3)
# print(x[..., 0, ...])


# Error since it is unclear what indiced are omitted

### 14

In [28]:
# "Что будет выведено на экран?"
# x = np.arange(16).reshape(4,4)
# # y = x[:, [2,3]]
# # y[:] = 0
# # print(x)
# # y = x[:,:2]
# # y[:] = 0
# # print(x)

# Advanced indexing returns a copy of an array, while basic indexing returns a view -> in the second case we obtain x with 0 in the first two columns

In [29]:
a = np.arange(1, 5).reshape(2, 2)

# Basic indexing 
b = a[(0, slice(None))]
b[0] = 100
a

array([[100,   2],
       [  3,   4]])

In [30]:
a = np.arange(1, 5).reshape(2, 2)

# Advanced indexing
b = a[(0, [0, 1])]
b[0] = 100
a

array([[1, 2],
       [3, 4]])

### 15
Замените отрицательные элементы массива нулем.

In [31]:
x = np.arange(-10, 10)
x[x < 0 ] = 0
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x = np.arange(-10, 10).reshape(4, 5)
x[x < 0] = 0
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 16
На примере целочисленного массива x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)
составьте новый массив, не содержащий строки, полностью заполненные одним уникальным значением


First solution 

In [33]:
x = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 1], [2, 2, 2], [2, 3, 1]], dtype=int)
y = np.any(x - x[:, 0, np.newaxis], axis=1)
x[y]

array([[1, 2, 3],
       [2, 2, 1],
       [2, 3, 1]])

Second solution

In [34]:
x = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 1], [2, 2, 2], [2, 3, 1]], dtype=int)
y = np.max(x, axis=1) != np.min(x, axis=1)
x[y]

array([[1, 2, 3],
       [2, 2, 1],
       [2, 3, 1]])

### 17
Для заданного одномерного массива x выведите все элементы, не превышающие своих соседей 
(первый и последний элемент сравниваются только со вторым и предпоследним соответственно)

First solution (bad solution)

In [35]:
x = np.random.choice(100, 100)

result = x[1:-1][(x[1:-1] <= np.roll(x, 1)[1:-1]) & (x[1:-1] <= np.roll(x, -1)[1:-1])]
if x[0] <= x[1]:
    result = np.insert(result, 0, x[0])
if x[-1] <= x[-2]:
    result = np.append(result, x[-1])
print(x)
result

[35  5 32  2  8 80  5 44 61 38 88 75 96 58 41 93 53 20 36  8 40 70 33 22
 68 39 38 65 42 36 62  0 96  8  6 20 47  9 49 62 35 86 69 80 74 12 46 72
 83 86 41 82 99 68 32 44 26 94 62 47 66 33 34 83 62 77 44 34 29 96 55 43
 19 66  2 30  9 75 29  6 78 77 90 32 60  5 33 19 44 24 60 62 26  4 44 30
 68  1 21 35]


array([ 5,  2,  5, 38, 75, 41, 20,  8, 22, 38, 36,  0,  6,  9, 35, 69, 12,
       41, 32, 26, 47, 33, 62, 29, 19,  2,  9,  6, 77, 32,  5, 19, 24,  4,
       30,  1])

Second solution

In [36]:
x = np.random.choice(10, 10)

mask = np.ones(x.shape, dtype=bool)
mask[1:] = x[1:] <= x[:-1]
mask[:-1] = mask[:-1] & (x[:-1] <= x[1:])
print(x)
print(mask)
x[mask]

[8 2 5 6 8 1 3 2 9 9]
[False  True False False False  True False  True False  True]


array([2, 1, 2, 9])

### 18
1. Создайте двумерный массив 3x3, заполненный случайными числами от 0 до 9
2. Отсортируйте строки массива по возрастанию значения во втором столбце

In [37]:
x = np.random.choice(10, (3, 3))
sort = x[:, 1].argsort()
print(x)
x[sort]

[[1 6 8]
 [3 3 7]
 [1 9 9]]


array([[3, 3, 7],
       [1, 6, 8],
       [1, 9, 9]])

In [38]:
x = np.array([[1, 2], [1, 0], [3, 4], [-1, 6]])
sort = np.lexsort((x[:, 1], x[:, 0]), axis=0) # sorts considering the priority 
print(x)
x[sort]

[[ 1  2]
 [ 1  0]
 [ 3  4]
 [-1  6]]


array([[-1,  6],
       [ 1,  0],
       [ 1,  2],
       [ 3,  4]])

### 19
Поменяйте местами первую и вторую строки двумерного массива

In [39]:
x = np.random.choice(10, (3, 3))
print(x)
x[[0, 1]] = x[[1, 0]]
print(x)

[[7 5 7]
 [4 8 7]
 [3 6 4]]
[[4 8 7]
 [7 5 7]
 [3 6 4]]


### 20 
1. Создайте массив 3x5, заполненный числами от 0 до 14
2. Выберите 1, 3 строки и 2, 4 столбцы, не удаляя элементы из массива

In [40]:
x = np.arange(15).reshape(3, -1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

First solution

In [41]:
x[[[0, 0], [2, 2]], [[1, 3], [1, 3]]]

array([[ 1,  3],
       [11, 13]])

Second solution 

In [42]:
x[np.ix_([0, 2], [1, 3])]

array([[ 1,  3],
       [11, 13]])

### 21

In [43]:
# "Что будет выведено на экран?
# x = np.arange(5)
# x[[0,0,1]] = range(3)
# print(x)
# x[[1,2,1]] += 1
# print(x)"

In [44]:
x = np.arange(5)
print(x)
x[[0, 0, 1]] = range(3)
print(x)
#print(x[[1, 2, 1]])
#x[[1, 2, 1]] = x[[1, 2, 1]] + 1
x[[1, 2, 1]] += 1
print(x)

[0 1 2 3 4]
[1 2 2 3 4]
[1 3 3 3 4]


### 22
Перечислите все известные вам способы преобразования заданного n-мерного массива в одномерный. Какой из способов работает быстрее и почему?

In [45]:
# np.ravel() - view or copy
# x.reshape() - view or copy 
# x.flatten() - always copy 

In [46]:
x = np.arange(4).reshape(2, 2)
x

array([[0, 1],
       [2, 3]])

In [47]:
%%time
y = np.ravel(x)
print(y)

[0 1 2 3]
CPU times: user 104 µs, sys: 298 µs, total: 402 µs
Wall time: 408 µs


In [48]:
%%time 
y = x.reshape(-1)
print(y)

[0 1 2 3]
CPU times: user 301 µs, sys: 126 µs, total: 427 µs
Wall time: 379 µs


In [49]:
%%time 
y = x.flatten()
print(y)

[0 1 2 3]
CPU times: user 753 µs, sys: 0 ns, total: 753 µs
Wall time: 592 µs


In [50]:
x = np.arange(4).reshape(2, 2)
x

array([[0, 1],
       [2, 3]])

In [51]:
z = x.ravel()
z[0] = 100
z, x
# create view of x 

(array([100,   1,   2,   3]),
 array([[100,   1],
        [  2,   3]]))

In [52]:
z = x.reshape(-1)
z[0] = 100
z, x
# create view of x 

(array([100,   1,   2,   3]),
 array([[100,   1],
        [  2,   3]]))

In [53]:
x = np.arange(4).reshape(2, 2)
y = x.T
y

array([[0, 2],
       [1, 3]])

In [54]:
y.flags, y.strides

(  C_CONTIGUOUS : False
   F_CONTIGUOUS : True
   OWNDATA : False
   WRITEABLE : True
   ALIGNED : True
   WRITEBACKIFCOPY : False
   UPDATEIFCOPY : False,
 (8, 16))

In [55]:
z = y.ravel()
z[0] = 100
y, z
# create copy of y

(array([[0, 2],
        [1, 3]]),
 array([100,   2,   1,   3]))

In [56]:
z = y.reshape(-1)
z[0] = 100
y, z
# create copy of y 

(array([[0, 2],
        [1, 3]]),
 array([100,   2,   1,   3]))

In [57]:
# Comparison of reshape order 
x = np.arange(12).reshape(3,4)
print(x)
print(x.reshape(-1, order='C'), 'C order')
print(x.reshape(-1, order='F'), 'F order')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11] C order
[ 0  4  8  1  5  9  2  6 10  3  7 11] F order


### 23
1. Создайте массив, заполненный случайными значениями
2. Замените максимальные значения массива средним

In [58]:
x = np.random.choice(100, 100000000)
x

array([80, 95, 62, ..., 47, 67, 47])

In [59]:
%%time
x[x == x.max()] = x.mean()
x

CPU times: user 261 ms, sys: 19.4 ms, total: 281 ms
Wall time: 279 ms


array([80, 95, 62, ..., 47, 67, 47])

In [60]:
%%time
np.place(x, x == x.max(), x.mean())
x

CPU times: user 267 ms, sys: 22.4 ms, total: 290 ms
Wall time: 287 ms


array([80, 95, 62, ..., 47, 67, 47])

### 24
1. Создайте двумерный массив 6x6, заполненный случайными значениями
2. Сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом

In [61]:
x = np.random.randn(6, 6)
x

array([[ 0.63298323, -1.65251806,  0.18594221,  1.46239351, -0.71153883,
         2.29189591],
       [-0.64515883, -0.4832852 , -2.23257634, -1.57393571, -0.87547779,
        -0.51321576],
       [ 0.34983658, -0.01737069, -0.98469901, -0.20891734, -1.22562164,
        -0.41427935],
       [ 0.01549992,  1.93769939, -0.1114446 ,  0.09309471, -0.12801932,
        -0.21737802],
       [-0.67191916,  0.5456176 , -0.79265763, -0.55198072, -1.62174791,
        -0.45428521],
       [ 1.2037921 , -0.07498868,  1.31018232, -0.12259327,  1.43391326,
         0.48387242]])

In [62]:
x.sum(axis=1) / x.min(axis=0)

array([-3.28783298,  3.82667505,  1.1202535 , -1.00985834,  2.1871297 ,
       -8.25028859])

### 25
Создайте одномерный массив длины 10, заполненный случайными значениями
Линейно отобразите элементы массива в отрезок [0, 1], при этом минимальный элемент должен отобразиться в 0, а максимальный - в 1

In [63]:
x = np.random.choice(10, 10)
x

array([5, 7, 4, 2, 5, 8, 4, 0, 1, 6])

In [64]:
(x - x.min()) / (x.max() - x.min())

array([0.625, 0.875, 0.5  , 0.25 , 0.625, 1.   , 0.5  , 0.   , 0.125,
       0.75 ])

### 26
Замените все вхождения nan в двумерный массив средним значением по соответствующему столбцу

In [65]:
x = np.array([[1, np.nan, 3], 
              [np.nan, 4, 5],
              [6, 7, np.nan]])
x

array([[ 1., nan,  3.],
       [nan,  4.,  5.],
       [ 6.,  7., nan]])

In [66]:
np.nan_to_num(x, nan=np.nanmean(x, axis=0))

array([[1. , 5.5, 3. ],
       [3.5, 4. , 5. ],
       [6. , 7. , 4. ]])

### 27
Проверьте, есть ли в двумерном массиве столбец, полностью заполненый нулями.

In [67]:
x = np.array([[1, 0, 3],
              [4, 0, 6],
              [7, 0, 9]])
x

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])

In [68]:
mask = ~np.any(x, axis=0)
print(mask)
if mask.sum():
    print(True)
else:
    print(False)

[False  True False]
True


### 28
1. Создайте массив случайных чисел от 0 до 9 размером 3x4x3x4
2. Вычислите суммы элементов по двум последним осям

In [69]:
x = np.random.choice(10, (3, 4, 3, 4))
print(x)
x.sum(axis=(2, 3))

[[[[8 4 9 9]
   [0 4 9 0]
   [7 9 8 0]]

  [[2 9 6 9]
   [1 8 0 7]
   [1 5 2 6]]

  [[5 0 5 2]
   [7 3 5 6]
   [0 3 7 6]]

  [[7 1 9 2]
   [7 0 1 4]
   [2 2 5 2]]]


 [[[1 0 0 6]
   [6 2 0 8]
   [5 1 5 7]]

  [[9 5 5 4]
   [1 6 1 9]
   [8 4 2 1]]

  [[3 9 5 7]
   [7 8 2 6]
   [9 8 7 2]]

  [[6 3 3 2]
   [4 4 7 0]
   [2 5 1 5]]]


 [[[3 8 6 4]
   [8 1 2 3]
   [4 3 9 7]]

  [[8 6 1 2]
   [7 8 5 0]
   [1 7 9 5]]

  [[6 4 9 6]
   [1 7 0 7]
   [9 2 1 7]]

  [[7 3 4 3]
   [2 4 7 7]
   [7 8 1 7]]]]


array([[67, 56, 49, 42],
       [41, 55, 73, 42],
       [58, 59, 59, 60]])

In [70]:
# We can decompose this operation into two sums
sum2 = x.sum(axis=2)
sum3 = sum2.sum(axis=-1)
sum3

array([[67, 56, 49, 42],
       [41, 55, 73, 42],
       [58, 59, 59, 60]])

### 29
1. Любым способом создайте два массива одинаковой длины
2. Создайте массив, в котором на четных позициях будут стоять элементы с соответствующих позиций первого массива, а на нечетных - с соответствующих позиций второго

In [71]:
x = np.random.choice(np.arange(100), 10000)
y = np.random.choice(np.arange(100, 200), 10000)
x, y

(array([51, 91, 56, ..., 93, 22, 31]),
 array([192, 188, 105, ..., 114, 131, 150]))

In [72]:
%%time
z = np.empty(x.shape)
z[1::2] = x[1::2]
z[::2] = y[::2]
z

CPU times: user 23 µs, sys: 38 µs, total: 61 µs
Wall time: 67.7 µs


array([192.,  91., 105., ...,  93., 131.,  31.])

In [73]:
%%time
arr = np.arange(x.shape[0]) % 2
np.where(arr, x, y)

CPU times: user 285 µs, sys: 468 µs, total: 753 µs
Wall time: 472 µs


array([192,  91, 105, ...,  93, 131,  31])

### 30
На примере массива x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]]) вычислите долю пропущенных значений

In [74]:
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
print(x)
np.isnan(x).mean()

[[ 1.  2.]
 [nan  3.]
 [ 5.  5.]
 [nan nan]]


0.375

### 31
На примере массива x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]]) составьте массив из уникальных значений массива без учета nan

In [75]:
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
print(x)
np.unique(x[~np.isnan(x)])

[[ 1.  2.]
 [nan  3.]
 [ 5.  5.]
 [nan nan]]


array([1., 2., 3., 5.])

### 32

На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит нулевой

In [76]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zeros_idx = np.where(x == 0)[0] + 1
zeros_idx = zeros_idx[zeros_idx < x.shape]
print(x[zeros_idx])
np.max(x[zeros_idx])

[3 0 5]


5

### 33

Пусть заданы два массива одинакового размера. Поэлементно разделите один массив на другой. В случае, если делитель равен нулю, соответствующему элементу результирующего массива присвойте нуль.

In [77]:
a = np.random.choice(10, 1000000)
b = np.random.choice(10, 1000000)
a[[0, 1]] = 2, 0
b[[0, 1]] = 0, 0 
print(a)
print(b)

[2 0 1 ... 7 6 2]
[0 0 9 ... 8 7 0]


In [78]:
%%timeit
np.divide(a, b, out=np.zeros(a.shape), where=(b != 0))

4.49 ms ± 22.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [79]:
%%timeit
np.where(b != 0, a / b, b)

<magic-timeit>:1: RuntimeWarning: divide by zero encountered in true_divide
<magic-timeit>:1: RuntimeWarning: invalid value encountered in true_divide


6.08 ms ± 138 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### 34

 Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

First solution (slow)

In [80]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5])
print(x)
print(i)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 5 5 5]


In [81]:
%%time
unique_values, counts = np.unique(i, return_counts=True) 
x[unique_values] += counts
x

CPU times: user 224 µs, sys: 160 µs, total: 384 µs
Wall time: 364 µs


array([2., 2., 2., 2., 1., 4., 1., 1., 1., 1.])

Second solution (the best)

In [82]:
x = np.ones(10)
i = np.array([1, 2, 3, 5, 5, 5, 8])
print(x)
print(i)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 2 3 5 5 5 8]


In [83]:
%%time
bins = np.bincount(i, minlength=len(x)) 
x += bins
x

CPU times: user 0 ns, sys: 93 µs, total: 93 µs
Wall time: 214 µs


array([1., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

Third solution (not good)

In [84]:
x = np.ones(10)
arr = np.array([1, 2, 3, 8, 5, 5, 8])
print(x)
print(i)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 2 3 5 5 5 8]


In [85]:
%%time
bins = np.bincount(i) 
x[:len(bins)] += bins
x

CPU times: user 39 µs, sys: 28 µs, total: 67 µs
Wall time: 60.3 µs


array([1., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

In [86]:
# Realization of np.unique() function from scratch
def unique(arr, return_counts=False, return_index=False, return_inverse=False):
    
    if return_inverse:
        sorting_idx = arr.argsort()
        sorted_arr = arr[sorting_idx]
    else:
        sorted_arr = np.sort(arr)

    counts = {}
    
    for val in sorted_arr:
        if val not in counts:
            counts[val] = 1
        else:
            counts[val] += 1
    
    mask = np.empty(sorted_arr.shape, dtype=bool)
    mask[0] = True
    mask[1:] = sorted_arr[1:] != sorted_arr[:-1]
    
    res = (np.array(list(counts.keys())), )
    
    if return_counts:
        res += (np.array(list(counts.values())), )
    
    if return_index:
        direct_idx = sorting_idx[mask]
        res += (direct_idx, )
    
    if return_inverse:
        mask_idx = np.cumsum(mask) - 1
        inv = np.empty(sorted_arr.shape, dtype=np.int64)
        inv[sorting_idx] = mask_idx
        res += (inv, )

    return res

In [87]:
arr = np.array([1, 2, 3, 8, 5, 5, 8])

In [88]:
np.unique(arr, return_counts=True, return_index=True, return_inverse=True)

(array([1, 2, 3, 5, 8]),
 array([0, 1, 2, 4, 3]),
 array([0, 1, 2, 4, 3, 3, 4]),
 array([1, 1, 1, 2, 2]))

In [89]:
uniq, counts, direct, inv = unique(arr, return_counts=True, return_index=True, return_inverse=True)
uniq, counts, direct,  inv

(array([1, 2, 3, 5, 8]),
 array([1, 1, 1, 2, 2]),
 array([0, 1, 2, 4, 3]),
 array([0, 1, 2, 4, 3, 3, 4]))

In [90]:
arr[direct] # return unique

array([1, 2, 3, 5, 8])

In [91]:
uniq[inv] # return arr 

array([1, 2, 3, 8, 5, 5, 8])

In [92]:
# Realization of np.bincount() function from scratch
def bincount(arr, minlength=0):
    """ My custom bincount. """
    dict_values = {}
    max_val = 0
    for i in range(len(arr)):
        if arr[i] > max_val:
            max_val = arr[i]
        if arr[i] not in dict_values:
            dict_values[arr[i]] = 1
        else:
            dict_values[arr[i]] += 1
            
    length = max(minlength, max_val + 1)
    output = np.zeros(length, dtype=np.int64)
    output[list(dict_values.keys())] = list(dict_values.values())
    
    return output

def bincount_src(arr, minlength=0):
    """ Bincount as source bincount in numpy. """
    res = np.zeros(minlength, dtype=np.int32)
    
    for val in arr:
        if val >= len(res):
            res = np.append(res, [0] * (val + 1 - len(res)))

        res[val] += 1

    return res

In [93]:
arr = np.array([0, 2, 3, 8, 5, 5, 8])

In [94]:
np.bincount(arr)

array([1, 0, 1, 1, 0, 2, 0, 0, 2])

In [95]:
bincount_src(arr)

array([1, 0, 1, 1, 0, 2, 0, 0, 2])

### 35

По заданному массиву y = np.bincount([0, 0, 3, 8, 10, 10, 11]) постройте массив x такой, чтобы np.bincount(x) = y

In [96]:
y = np.bincount([0, 0, 3, 8, 10, 10, 11])
y

array([2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 2, 1])

First solution 

In [97]:
def restore_bincount(y):
    
    values = y.nonzero()[0] # choose non zero indexes 
    x = []
    for val in values:
        x.extend([val] * y[val])
        
    return np.array(x)

In [98]:
restore_bincount(y)

array([ 0,  0,  3,  8, 10, 10, 11])

In [99]:
%%timeit 
restore_bincount(y)

3.26 µs ± 37.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Second solution

In [100]:
values = y.nonzero()[0]
np.repeat(values, y[values])

array([ 0,  0,  3,  8, 10, 10, 11])

In [101]:
%%timeit 
values = y.nonzero()[0]
np.repeat(values, y[values])

1.59 µs ± 25.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Third solution (the best)

In [102]:
np.repeat(np.arange(len(y)), y)

array([ 0,  0,  3,  8, 10, 10, 11])

In [103]:
%%timeit
np.repeat(np.arange(len(y)), y)

1.59 µs ± 9.64 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### 36
Определите самые часто встречающиеся элементы в массиве целых неотрицательных чисел.
Решите задачу на примере массива x = np.array([0,1,2,0,6,6,7,4,5,4]).

In [104]:
x = np.array([0, 1, 2, 0, 6, 6, 7, 4, 5, 4])

First solution

In [105]:
%%time
values, counts = np.unique(x, return_counts=True)
values[counts == np.max(counts)]

CPU times: user 264 µs, sys: 50 µs, total: 314 µs
Wall time: 300 µs


array([0, 4, 6])

Second solution

In [106]:
%%time
bins = np.bincount(x)
(bins == np.max(bins)).nonzero()[0]

CPU times: user 92 µs, sys: 18 µs, total: 110 µs
Wall time: 111 µs


array([0, 4, 6])

### 37

"Разбейте двумерный массив на список двумерных массивов по уникальным значениям в первом столбце.
Решите задачу на примере массива x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]]), в результате должен получиться список [array([[1, 2], [1, 3]]), array([[2, 2]]), array([[3, 4], [3, 5]])]."

First solution

In [107]:
%%time
x = np.array([[1, 2], [2, 2], [1, 3], [3, 4], [3, 5], [5, 17], [3, 6]])
#x = np.random.choice(100, (10, 10))
idx = np.argsort(x[:, 0], axis=0)
sorted_x = x[idx]
diff = np.diff(sorted_x[:, 0], axis=0) # output: [0, 1, 1, 0, 0, 2]
split_idx = np.where(diff != 0)[0] + 1
split_arr_1 = np.split(sorted_x, split_idx) # output: [array[:2], array[2:3], array[3:6], array[6:]]
split_arr_1

CPU times: user 250 µs, sys: 47 µs, total: 297 µs
Wall time: 293 µs


[array([[1, 2],
        [1, 3]]),
 array([[2, 2]]),
 array([[3, 4],
        [3, 5],
        [3, 6]]),
 array([[ 5, 17]])]

Second solution

In [108]:
%%time
x = np.array([[1, 2], [2, 2], [1, 3], [3, 4], [3, 5], [5, 17], [3, 6]])
first_column = x[:, 0]
idx = np.argsort(first_column, axis=0)
sorted_x = x[idx]
values, counts = np.unique(first_column, return_counts=True)
split_idx = np.cumsum(counts)[:-1]
split_arr_2 = np.split(sorted_x, split_idx)
split_arr_2

CPU times: user 193 µs, sys: 36 µs, total: 229 µs
Wall time: 219 µs


[array([[1, 2],
        [1, 3]]),
 array([[2, 2]]),
 array([[3, 4],
        [3, 5],
        [3, 6]]),
 array([[ 5, 17]])]

In [109]:
%%timeit
x = np.array([[1, 2], [2, 2], [1, 3], [3, 4], [3, 5], [5, 17], [3, 6]])
#x = np.random.choice(100, (10, 10))
idx = np.argsort(x[:, 0], axis=0)
sorted_x = x[idx]
diff = np.diff(sorted_x, axis=0)[:, 0] # output: [0, 1, 1, 0, 0, 2]
split_idx = np.where(diff != 0)[0] + 1
split_arr_1 = np.split(sorted_x, split_idx) # output: [array[:2], array[2:3], array[3:6], array[6:]]
split_arr_1

23.2 µs ± 50.5 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [110]:
%%timeit
x = np.array([[1, 2], [2, 2], [1, 3], [3, 4], [3, 5], [5, 17], [3, 6]])
first_column = x[:, 0]
idx = np.argsort(first_column, axis=0)
sorted_x = x[idx]
values, counts = np.unique(first_column, return_counts=True)
split_idx = np.cumsum(counts)[:-1]
split_arr_2 = np.split(sorted_x, split_idx)
split_arr_2

35.9 µs ± 216 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### 38

"По заданному одномерному массиву неотрицательных чисел постройте список подмассивов, сожержащих элементы из полуинтервалов [i * 10, (i+1) * 10), i = 0, 1, 2, …
Решите задачу на примере массива x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20]), в результате должен получиться список [array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])]."

In [111]:
%%time
x = np.array([8, 2, 50, 1, 11, 18, 13, 2, 24, 10, 20])
x = np.sort(x)
intervals = 10 * np.arange(x.max() // 10 + 1)[1:]
split_idx = np.searchsorted(x, intervals)
np.split(x, split_idx)

CPU times: user 510 µs, sys: 0 ns, total: 510 µs
Wall time: 512 µs


[array([1, 2, 2, 8]),
 array([10, 11, 13, 18]),
 array([20, 24]),
 array([], dtype=int64),
 array([], dtype=int64),
 array([50])]

In [112]:
print(intervals)
print(split_idx)

[10 20 30 40 50]
[ 4  8 10 10 10]


### 39

Перечислите все известные вам способы соединения заданных двумерных массивов по вертикали. Какой из способов работает быстрее?

In [113]:
x = np.arange(1000000).reshape(1000, 1000)
y = np.random.choice(10000, (1000, 1000))

In [114]:
%%timeit
np.vstack((x, y))

1.29 ms ± 6.11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [115]:
%%timeit
np.row_stack((x, y))

1.28 ms ± 6.38 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [116]:
%%timeit
np.stack((x, y), axis=0) # creates new axis, output shape (2, m, n)

1.29 ms ± 9.51 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [117]:
%%timeit
np.concatenate((x, y), axis=0)

1.29 ms ± 9.69 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [118]:
%%timeit
np.concatenate((x[None], y[None]), axis=0)

1.29 ms ± 14.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [119]:
%%timeit
np.block([[x], [y]])

1.32 ms ± 6.72 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [120]:
%%timeit
np.append(x, y, axis=0)

1.29 ms ± 9.01 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### 40

Для двух одномерных массивов x = np.arange(3) и y = np.arange(5) постройте двумерный массив строки которого - всевозможные пары элементов из x и y.

In [121]:
x = np.arange(3)
y = np.arange(5)

Some notes

In [122]:
xx, yy = np.meshgrid(x, y)
xx, yy

(array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]))

In [123]:
a = np.array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])
b = np.array([0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

c = np.vstack((a, b))
c, c.T

(array([[1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]]),
 array([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0]]))

First solution

In [124]:
%%time
xx, yy = np.meshgrid(x, y)
xy_pairs = np.vstack((xx.reshape(-1), yy.reshape(-1))).T
xy_pairs

CPU times: user 141 µs, sys: 9 µs, total: 150 µs
Wall time: 157 µs


array([[0, 0],
       [1, 0],
       [2, 0],
       [0, 1],
       [1, 1],
       [2, 1],
       [0, 2],
       [1, 2],
       [2, 2],
       [0, 3],
       [1, 3],
       [2, 3],
       [0, 4],
       [1, 4],
       [2, 4]])

Second solution

In [125]:
%%time
xx, yy = np.meshgrid(x, y)
xy_pairs = np.column_stack((xx.reshape(-1), yy.reshape(-1)))
xy_pairs

CPU times: user 212 µs, sys: 13 µs, total: 225 µs
Wall time: 210 µs


array([[0, 0],
       [1, 0],
       [2, 0],
       [0, 1],
       [1, 1],
       [2, 1],
       [0, 2],
       [1, 2],
       [2, 2],
       [0, 3],
       [1, 3],
       [2, 3],
       [0, 4],
       [1, 4],
       [2, 4]])

Third solution 

In [126]:
%%time
xx, yy = np.meshgrid(x, y)
xy_pairs = np.transpose(np.array((xx, yy)), axes=(2, 1, 0)).reshape(-1, 2)
xy_pairs

CPU times: user 132 µs, sys: 8 µs, total: 140 µs
Wall time: 147 µs


array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4]])

### 41

"По двум входным одномерным массивам одинаковой длины составьте массив пар элементов с одинаковыми индесами.
Решите задачу на примере массивов x = np.array([1,2,3,4]) и y = np.array([5,6,7,8])."

In [127]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

First solution

In [128]:
%%timeit
np.column_stack((x, y))

3.26 µs ± 20 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [129]:
np.column_stack((x, y))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Second solution

In [130]:
%%timeit
np.vstack((x, y)).T

4.09 µs ± 12.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [131]:
np.vstack((x, y)).T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### 42

"По заданному непустому списку двумерных массивов одинаковых размеров составьте трехмерный массив в котором вдоль нулевой оси расположены массивы из списка, между каждой парой которых вставлен массив полностью заполненный нулями.
Решите задачу для списка l = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])]."

In [132]:
l = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])]

First solution

In [133]:
%%timeit
res = [np.zeros_like(l[0])] * (2 * len(l) - 1)
res[::2] = l
np.stack(res)

10.5 µs ± 42.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [134]:
res = [np.zeros_like(l[0])] * (2 * len(l) - 1)
res[::2] = l
np.stack(res)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 0,  0],
        [ 0,  0]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 0,  0],
        [ 0,  0]],

       [[ 9, 10],
        [11, 12]]])

Second solution

In [135]:
%%timeit
output_shape = len(l) + len(l) - 1, l[0].shape[0], l[0].shape[1]
output = np.zeros(output_shape)
stacked_arr = np.stack(l)
output[::2] += stacked_arr
output

8.75 µs ± 44 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [136]:
output_shape = len(l) + len(l) - 1, l[0].shape[0], l[0].shape[1]
output = np.zeros(output_shape, dtype=l[0].dtype)
stacked_arr = np.stack(l)
output[::2] += stacked_arr
output

array([[[ 1,  2],
        [ 3,  4]],

       [[ 0,  0],
        [ 0,  0]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 0,  0],
        [ 0,  0]],

       [[ 9, 10],
        [11, 12]]])

### 43

Преобразуйте одномерный массив x = np.array([3,7,2,5,0,9,8,2,4,5]) в двумерный массив, первая строка которого - элементы массива x с индексами от 0 до 4, вторая строка - с 1 до 5 и т.д.

In [137]:
from numpy.lib.stride_tricks import as_strided

In [138]:
x = np.array([3, 7, 2, 5, 0, 9, 8, 2, 4, 5, 6])
as_strided(x, shape=(x.shape[0] - 4, 5), strides=(8, 8))

array([[3, 7, 2, 5, 0],
       [7, 2, 5, 0, 9],
       [2, 5, 0, 9, 8],
       [5, 0, 9, 8, 2],
       [0, 9, 8, 2, 4],
       [9, 8, 2, 4, 5],
       [8, 2, 4, 5, 6]])

Some exercises

In [139]:
x = np.arange(1, 26).reshape(5, 5).astype(np.int64)
print(x)
as_strided(x, shape=(3, ), strides=(8, ))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([1, 2, 3])

In [140]:
as_strided(x, shape=(x.size, ), strides=(8,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [141]:
as_strided(x, shape=(3, ), strides=(16, ))

array([1, 3, 5])

In [142]:
as_strided(x, shape=(4, ), strides=(40, ))

array([ 1,  6, 11, 16])

In [143]:
as_strided(x, shape=(x.shape[0],), strides=(48, ))

array([ 1,  7, 13, 19, 25])

In [144]:
as_strided(x, shape=(4, 2), strides=(48, 8)) # zigzag

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]])

In [145]:
print(x)
as_strided(x, shape=(3, 3), strides=(80, 16))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

In [146]:
print(x)
as_strided(x, shape=(3, 3), strides=(8, 40))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13]])

In [147]:
as_strided(x, shape=(5, 4), strides=(40, 0))

array([[ 1,  1,  1,  1],
       [ 6,  6,  6,  6],
       [11, 11, 11, 11],
       [16, 16, 16, 16],
       [21, 21, 21, 21]])

In [148]:
x = np.arange(1, 13).reshape(3, 2, 2)
print(x.strides)
x

(32, 16, 8)


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [149]:
as_strided(x, shape=(3, 4), strides=(32, 8))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [150]:
x = np.arange(1, 26).reshape(5, 5).astype(np.int64)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [151]:
as_strided(x, shape=(2, 2, 2), strides=(120, 40, 8))

array([[[ 1,  2],
        [ 6,  7]],

       [[16, 17],
        [21, 22]]])

In [152]:
as_strided(x, shape=(2, 2, 3), strides=(80, 48, 8))

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [17, 18, 19]]])

In [153]:
x = np.arange(1, 21).reshape(4, 5)
as_strided(x, shape=(3, 2, 5), strides=(40, 40, 8))

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

### 44

"Для заданного двумерного массива постройте трехмерный массив, содержащий всевозможные неперекрывающиеся блоки размера 3x3, начиная с левого верхнего угла. Если высота/ширина исходного массива не кратна трем, исключите из рассмотрения последние строки/столбцы.
Решите задачу на примере массива x = np.arange(49).reshape(7,7)."

In [154]:
def make_windows(arr, window_size=3):
    
    shape_0 = arr.shape[0] // window_size
    shape_1 = arr.shape[1] // window_size
    
    stride_0 = window_size * arr.shape[1] * arr.itemsize # 3 x 7 x 8
    stride_1 = window_size * arr.itemsize # 3 x 8
    stride_2 = arr.shape[1] * arr.itemsize # 7 x 8
    stride_3 = arr.itemsize # 8
    
    new_arr = as_strided(arr, shape=(shape_0, shape_1, window_size, window_size), strides=(stride_0, stride_1, stride_2, stride_3))
    new_arr = new_arr.reshape(shape_0 * shape_1, window_size, window_size)
    
    return new_arr

In [155]:
x = np.arange(49).reshape(7, 7)
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [156]:
make_windows(x)

array([[[ 0,  1,  2],
        [ 7,  8,  9],
        [14, 15, 16]],

       [[ 3,  4,  5],
        [10, 11, 12],
        [17, 18, 19]],

       [[21, 22, 23],
        [28, 29, 30],
        [35, 36, 37]],

       [[24, 25, 26],
        [31, 32, 33],
        [38, 39, 40]]])

### 45

"Примените маску к элементам одномерного массива, отличающимся от среднего на величину, большую чем 3 стандартных отклонения.
Решите задачу на примере массива из 20 элеметнов, первый из которых равен 100, а остальные равны 0."

In [157]:
import numpy.ma as ma

x = np.zeros(20)
x[0] = 100
# x[1] = -100

First solution

In [158]:
m = ma.masked_where(np.abs(x - x.mean()) > 3 * x.std(), x)
m

masked_array(data=[--, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
             mask=[ True, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=1e+20)

Second solution

In [159]:
m = ma.masked_greater(x, x.mean() + 3 * x.std())
m

masked_array(data=[--, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
             mask=[ True, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=1e+20)

### 46
"Удалите из двумерного массива столбцы, ко всем элементам которых применена маска.
Решите задачу на примере массива x = np.ma.array([[1, 2, 3], [4, 5, 6]], mask=[[1, 1, 0], [0, 1, 0]])."

In [160]:
x = np.ma.array([[1, 2, 3, 6], [4, 5, 6, 7]], mask=[[1, 1, 0, 1], [0, 1, 0, 1]])
print(x)
x.mask

[[-- -- 3 --]
 [4 -- 6 --]]


array([[ True,  True, False,  True],
       [False,  True, False,  True]])

In [161]:
o = x[:, ~np.all(x.mask, axis=0)]
o.data

array([[1, 3],
       [4, 6]])

### 47
"Примените маску к минимальному и максимальному элементу каждой строки двумерного массива.
Решите задачу на примере массива x = np.arange(25).reshape(5, 5)."

In [162]:
x = np.arange(25).reshape(5, 5)
print(x)
mask = (x == x.max(axis=-1, keepdims=True)) | (x == x.min(axis=-1, keepdims=True))
mask

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ True, False, False, False,  True],
       [ True, False, False, False,  True],
       [ True, False, False, False,  True],
       [ True, False, False, False,  True],
       [ True, False, False, False,  True]])

In [163]:
m = ma.masked_array(x, mask=mask)
m

masked_array(
  data=[[--, 1, 2, 3, --],
        [--, 6, 7, 8, --],
        [--, 11, 12, 13, --],
        [--, 16, 17, 18, --],
        [--, 21, 22, 23, --]],
  mask=[[ True, False, False, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False,  True]],
  fill_value=999999)

### 48
"Примените медианный фильтр с нечетной шириной окна k к заданному одномерному массиву a: i-е значение результирующего массива вычисляется как медиана подмассива a[i - (k-1)/2: i - (k-1)/2 + 1]. В случае если границы окна выходят за границы массива, дополните исходный массив требуемым числом элементов a[0] или a[-1] с нужной стороны.
Решите задачу на примере массива a = np.array([3, 8, 100, -3, -7, 4, 0, 2]) и ширины окна k = 5."

In [164]:
a = np.array([3, 8, 100, -3, -7, 4, 0, 2])
k = 5
padding = (k - 1) // 2
a_pad = np.pad(a, pad_width=(padding, padding), mode='edge')

In [165]:
%%time
patches = np.lib.stride_tricks.sliding_window_view(a_pad, window_shape=5)
np.median(patches, axis=-1)

CPU times: user 593 µs, sys: 32 µs, total: 625 µs
Wall time: 527 µs


array([3., 3., 3., 4., 0., 0., 2., 2.])

In [166]:
%%time
output = np.empty(a.shape, dtype=a.dtype)
k = 5
w = (k - 1) // 2

for i in range(w, a_pad.shape[0] - w):
    output[i - w] = np.median(a_pad[i - w: i + w + 1])
output

CPU times: user 653 µs, sys: 0 ns, total: 653 µs
Wall time: 526 µs


array([3, 3, 3, 4, 0, 0, 2, 2])

### 49
"По заданному массиву a размера Nx2 постройте одномерный массив длины N, i-й элемент которого - сумма i-го элемента первого столбца массива a и элемента первого столбца, индекс которого содержится в i-й строке второго столбца. В случае, если во втором столбце массива a содержится индекс, выходящий за границы, к элементу первого столбца ничего не прибавляйте.
Решите задачу на примере массива a = np.array([[10, 1], [3, 1], [8, 2], [6, 1], [12, 5]])."

In [167]:
a = np.array([[10, 1], [3, 1], [8, 2], [6, 1], [12, 5], [7, 9]])
a

array([[10,  1],
       [ 3,  1],
       [ 8,  2],
       [ 6,  1],
       [12,  5],
       [ 7,  9]])

First solution

In [168]:
%%timeit
output = a[:, 0].copy()
second_column = a[:, 1]
mask = second_column < a.shape[0]
idxes = second_column[mask]
output[mask] += output[idxes]
output

3.18 µs ± 24.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [169]:
%%time
output = a[:, 0].copy()
second_column = a[:, 1]
mask = second_column < a.shape[0]
idxes = second_column[mask]
output[mask] += output[idxes]
output

CPU times: user 36 µs, sys: 2 µs, total: 38 µs
Wall time: 34.3 µs


array([13,  6, 16,  9, 19,  7])

Second solution

In [170]:
%%timeit
output = a[:, 0].copy()
for i in range(output.shape[0]):
    idx = a[i, 1]
    output[i] += a[idx, 0] if idx < a.shape[0] else 0
output

3.93 µs ± 11.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [171]:
%%time
output = a[:, 0].copy()
for i in range(output.shape[0]):
    idx = a[i, 1]
    output[i] += a[idx, 0] if idx < a.shape[0] else 0
output

CPU times: user 43 µs, sys: 3 µs, total: 46 µs
Wall time: 42 µs


array([13,  6, 16,  9, 19,  7])

### 50
"По заданному двумерному массиву размера NxN постройте словарь, ключи которого - индексы диагоналей, параллельных побочной (нумерация начинается с 0), а значения - списки элементов исходного массива, лежащих на соответствующих диагоналях.
Решите задачу на примере массива a = np.arange(16).reshape(4, 4), в результате должен получиться словарь
{0: [0],
 1: [1, 4],
 2: [2, 5, 8],
 3: [3, 6, 9, 12],
 4: [7, 10, 13],
 5: [11, 14],
 6: [15]}."

In [172]:
a = np.arange(16).reshape(4, 4)

First solution

In [173]:
flipped_a = np.fliplr(a)
a, flipped_a

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8],
        [15, 14, 13, 12]]))

In [174]:
%%time
shape = a.shape[0]
flipped_a = np.fliplr(a)
d = {shape -1 - i: flipped_a.diagonal(i) for i in range(shape - 1, -shape, -1)}
d

CPU times: user 37 µs, sys: 2 µs, total: 39 µs
Wall time: 42.9 µs


{0: array([0]),
 1: array([1, 4]),
 2: array([2, 5, 8]),
 3: array([ 3,  6,  9, 12]),
 4: array([ 7, 10, 13]),
 5: array([11, 14]),
 6: array([15])}

Second solution (not good)

In [175]:
from collections import defaultdict

In [176]:
%%time
d = defaultdict(list)
for i, val in np.ndenumerate(a):
    d[np.sum(i)].append(val)
d

CPU times: user 249 µs, sys: 13 µs, total: 262 µs
Wall time: 268 µs


defaultdict(list,
            {0: [0],
             1: [1, 4],
             2: [2, 5, 8],
             3: [3, 6, 9, 12],
             4: [7, 10, 13],
             5: [11, 14],
             6: [15]})